In [5]:
import pandas as pd
import numpy as np
import Preprocess

In [4]:
!pip install pydicom

     |████████████████████████████████| 7.1MB 6.1MB/s eta 0:00:01


In [13]:
path = '/Users/juhyeoksin/Documents'
preprocess = Preprocess.Preprocess(path)

In [14]:
labels = preprocess.label_set('stage_1_train.csv')

In [15]:
labels.head()

ID  Label          Sub_type  PatientID
361025               ID_000039fa0_any      0               any  000039fa0
361020          ID_000039fa0_epidural      0          epidural  000039fa0
361021  ID_000039fa0_intraparenchymal      0  intraparenchymal  000039fa0
361022  ID_000039fa0_intraventricular      0  intraventricular  000039fa0
361023      ID_000039fa0_subarachnoid      0      subarachnoid  000039fa0

In [23]:
# !cat -n Preprocess.py

In [32]:
path_dcmFiles = '/Users/juhyeoksin/Documents/input/rsna-intracranial-hemorrhage-detection/stage_1_train_images/*.dcm'
dcm_files = Preprocess.Preprocess.read_dcm_files(path_dcmFiles)

In [33]:
normalized_dcm_list = preprocess.transform_all_pixel_arrays(dcm_files)

In [37]:
type(normalized_dcm_list)

list

In [38]:
training_images = np.array(normalized_dcm_list)

In [56]:
training_images = training_images.reshape(1000, 512, 512, 1)

In [57]:
training_images.shape

(1000, 512, 512, 1)

In [42]:
type(labels)

pandas.core.frame.DataFrame

In [73]:
label_list = np.array(labels['Label'])

In [74]:
type(label_list)

numpy.ndarray

In [75]:
label_list.shape

(6000,)

In [100]:
label_list[12*6:13*6]

array([1, 0, 1, 0, 0, 0])

In [76]:
label_list[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
sliced = slice(0, len(label_list), 6)

TypeError: 'slice' object is not callable

In [95]:
train_label = []
for i in range(0, len(label_list), 6):
    temp = label_list[i:i+6]
    flag = False
    index = 10
    for j in range(0, len(temp)):
        if temp[j] == 1:
            flag = True
            index = j
    if flag == True:
        train_label.append(index)
    else:
        train_label.append(6)
        

In [96]:
len(train_label)

1000

In [98]:
# train_label

In [89]:
type(train_label)

list

In [90]:
train_label

[array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([1, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 1]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 

In [101]:
import tensorflow as tf

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(512, 512, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(7, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 510, 510, 64)      640       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 255, 255, 64)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 253, 253, 64)      36928     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 126, 126, 64)      0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1016064)           0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               130056320 
_________________________________________________________________
dense_3 (Dense)              (None, 7)                

In [ ]:
model.fit(training_images, train_label, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 3066s 3s/sample - loss: 1.2891 - acc: 0.8240
Epoch 2/5
 704/1000 [====================>.........] - ETA: 12:22 - loss: 0.3950 - acc: 0.8693