In [2]:
import pandas as pd
import numpy as np
import Preprocess
import pydicom
import matplotlib.pyplot as plt

In [3]:
!pip install pydicom

In [4]:
path = '/home/juhyeok/Documents/RSNA'
preprocess = Preprocess.Preprocess(path)

In [5]:
labels = preprocess.label_set('stage_1_train.csv')

In [6]:
labels.head()

ID  Label          Sub_type  PatientID
361025               ID_000039fa0_any      0               any  000039fa0
361020          ID_000039fa0_epidural      0          epidural  000039fa0
361021  ID_000039fa0_intraparenchymal      0  intraparenchymal  000039fa0
361022  ID_000039fa0_intraventricular      0  intraventricular  000039fa0
361023      ID_000039fa0_subarachnoid      0      subarachnoid  000039fa0

In [7]:
# labels = labels['Label']

In [8]:
len(labels)

6000

In [9]:
label_list = np.array(labels['Label'])
# type(label_list)
# label_list.shape

train_label = []
for i in range(0, len(label_list), 6):
    temp = label_list[i:i+6]
    flag = False
    index = 10
    for j in range(0, len(temp)):
        if temp[j] == 1:
            flag = True
            index = j
    if flag == True:
        train_label.append(index)
    else:
        train_label.append(6)

len(train_label)
# type(train_label)

1000

In [10]:
# !cat -n Preprocess.py

In [11]:
path_dcmFiles = '/home/juhyeok/Documents/RSNA/input/rsna-intracranial-hemorrhage-detection/stage_1_train_images/*.dcm'
dcm_files = Preprocess.Preprocess.read_dcm_files(path_dcmFiles)

In [12]:
!pip install pydicom

In [13]:
data = pydicom.dcmread(dcm_files[0])

In [14]:
window_center, window_width, intercept, slope = preprocess.get_windowing(data)

In [15]:
type(data.pixel_array)

numpy.ndarray

In [16]:
np.amin(data.pixel_array)

-2000

In [17]:
np.amax(data.pixel_array)

2848

In [18]:
type(pydicom)

module

In [19]:
type(dcm_files)
# len(dcm_files)

list

In [20]:
before_decimalized = []

for dcm_file in dcm_files:
    data = pydicom.dcmread(dcm_file)
    window_center, window_width, intercept, slope = preprocess.get_windowing(data)
    pixel_array = data.pixel_array
    pixel_array_HU = preprocess.window_image(pixel_array, window_center, window_width, intercept, slope)
    before_decimalized.append(pixel_array_HU)

In [21]:
# min = np.amin(before_decimalized[0])
# max = np.amax(before_decimalized[0])
# print(f'(min, max) = {min, max}')

good_arrays = []
# if element == 1, corresponding image is not broken. element == 0, otherwise
good_index = []
for bd in before_decimalized:
    min = np.amin(bd)
    max = np.amax(bd)
    if (max - min) > 0:
        good_index.append(1)
        good_arrays.append(bd)
    else:
        good_index.append(0)

In [22]:
len(good_arrays)

987

In [23]:
len(good_index)

1000

In [24]:
good_labels = []
for i in range(len(train_label)):
    if good_index[i] == 1:
        good_labels.append(train_label[i])

In [25]:
len(good_labels)

987

In [26]:
good_index

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [27]:
# for i in range(len(good_index)):
#     if i != good_index[i]:
#         print(f'a wrong indexing: {good_index[i]}')

In [28]:
bad_arrays = []
for bd in before_decimalized:
    min = np.amin(bd)
    max = np.amax(bd)
    if (max - min) <= 0:
        bad_arrays.append(bd)

In [29]:
# len(bad_arrays)

In [30]:
for ba in good_arrays:
    min = np.amin(ba)
    max = np.amax(ba)
    print(f'(min, max) = {min, max}')

(min, max) = (-10, 70)
(min, max) = (0, 100)
(min, max) = (0, 80)
(min, max) = (-32, 102)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (0, 80)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (0, 100)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-35, 115)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-32, 102)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-35, 115)
(min, max

(min, max) = (-35, 115)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-32, 102)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-15, 85)
(min, max) = (-32, 102)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-35, 115)
(min, max) = (-35, 115)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-32, 102)
(min, max) = (-10, 70)
(min, max) = (-4, 76)
(min, max) = (-4, 76)
(min, max) = (-15, 85)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (0, 100)
(min, max) = (-4, 76)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-10, 70)
(min, max) = (-35, 115)
(min, max) = (-10, 70)
(min, max) = (-4, 7

In [31]:
for ba in bad_arrays:
    min = np.amin(ba)
    max = np.amax(ba)
    print(f'(min, max) = {min, max}')

(min, max) = (0, 0)
(min, max) = (-4, -4)
(min, max) = (-4, -4)
(min, max) = (0, 0)
(min, max) = (-4, -4)
(min, max) = (-4, -4)
(min, max) = (-4, -4)
(min, max) = (7, 7)
(min, max) = (-4, -4)
(min, max) = (-4, -4)
(min, max) = (-4, -4)
(min, max) = (-4, -4)
(min, max) = (-4, -4)


In [32]:
good_labels # 987 labels
good_arrays # 987 training mages

[array([[-10, -10, -10, ..., -10, -10, -10],
        [-10, -10, -10, ..., -10, -10, -10],
        [-10, -10, -10, ..., -10, -10, -10],
        ...,
        [-10, -10, -10, ..., -10, -10, -10],
        [-10, -10, -10, ..., -10, -10, -10],
        [-10, -10, -10, ..., -10, -10, -10]], dtype=int16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32),
 array([[-32, -32, -32, ..., -32, -32, -32],
        [-32, -32, -32, ..., -32, -32, -32],
        [-32, -32, -32, ..., -32, -32, -32],
        ...,
        [-32, -32, -32, ..., -32, -32, -32],
        [-32, -32, -32, ..., -32, -32, -32],
        [-32

In [33]:
# normalized_dcm_list = preprocess.transform_all_pixel_arrays(good_files)

In [34]:
# normalized_dcm_list[50:100]

In [35]:
# type(normalized_dcm_list)

In [36]:
training_images = np.array(good_arrays)

In [37]:
training_images = training_images.reshape(987, 512, 512, 1)

In [38]:
training_images.shape

(987, 512, 512, 1)

In [39]:
type(good_labels)

list

In [40]:
# label_list[12*6:13*6]

In [41]:
# label_list[:100]

In [42]:
training_label = np.array(good_labels)

In [43]:
type(training_label)

numpy.ndarray

In [44]:
# !pip install tensorflow

In [45]:
import tensorflow as tf

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(512, 512, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(7, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 510, 510, 64)      640       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 255, 255, 64)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 253, 253, 64)      36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 126, 126, 64)      0         
_________________________________________________________________
flatten (Flatten)            (None, 1016064)           0         
_________________________________________________________________
dense (Dense)                (None, 128)               130056320 
_________________________________________________________________
dense_1 (Dense)              (None, 7)                 9

In [46]:
model.fit(training_images, training_label, epochs=5)

Train on 987 samples
Epoch 1/5
987/987 [==============================] - 165s 168ms/sample - loss: 112.1804 - accuracy: 0.7447
Epoch 2/5
987/987 [==============================] - 160s 162ms/sample - loss: 0.8176 - accuracy: 0.8693
Epoch 3/5
987/987 [==============================] - 159s 161ms/sample - loss: 0.2836 - accuracy: 0.9240
Epoch 4/5
987/987 [==============================] - 178s 180ms/sample - loss: 0.0960 - accuracy: 0.9828
Epoch 5/5
987/987 [==============================] - 161s 163ms/sample - loss: 0.0207 - accuracy: 0.9970
